feat: add  virtualisation

diff --git a/.chezmoiscripts/run_onchange_before_01-install-arch-packages.sh.tmpl b/.chezmoiscripts/run_onchange_before_01-install-arch-packages.sh.tmpl
--- a/.chezmoiscripts/run_onchange_before_01-install-arch-packages.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_before_01-install-arch-packages.sh.tmpl
@@ -1,11 +1,19 @@
 #!/usr/bin/env bash
 # vim: filetype=bash
 
+set -euo pipefail
 export PATH="$HOME/.local/bin/:$PATH"
+
+
+# Pretty print functions
+info()    { echo -e "\033[1;34m[INFO]\033[0m $*"; }
+warn()    { echo -e "\033[1;33m[WARN]\033[0m $*"; }
+error()   { echo -e "\033[1;31m[ERROR]\033[0m $*"; }
+success() { echo -e "\033[1;32m✅ $*\033[0m"; }
 
 {{ if eq .chezmoi.osRelease.idLike "arch" }}
 
-echo "Installing Arch packages"
+info "Installing Arch packages"
 
 sudo pacman -Syu --noconfirm --needed {{ range .packages.linux.arch.core }} {{.}}{{end}} {{ range .packages.linux.arch.extra }} {{.}}{{end}} {{ range .packages.linux.arch.multilib }} {{.}}{{end}}
 
@@ -17,11 +25,12 @@ elif type -P yay >/dev/null 2>&1; then
   yay -Syu --noconfirm --needed {{ range .packages.linux.arch.aur }} {{.}}{{ end }}
 fi
 
+success "Installed Arch packages"
 
 
 {{ else }}
 
-echo "This script is only for Arch based systems. Exiting..."
+error "This script is only for Arch based systems. Exiting..."
 exit 1
 
 {{ end }}
