fix, chore: fix openclaw uninstall and add download local models ollama flag

diff --git a/home/.chezmoiscripts/run_onchange_after_505-install-ollama-models.sh.tmpl b/home/.chezmoiscripts/run_onchange_after_505-install-ollama-models.sh.tmpl
--- a/home/.chezmoiscripts/run_onchange_after_505-install-ollama-models.sh.tmpl
+++ b/home/.chezmoiscripts/run_onchange_after_505-install-ollama-models.sh.tmpl
@@ -1,27 +1,27 @@
 #!/usr/bin/env bash
 
-{{ if eq .chezmoi.os "linux" -}}
-set -euo pipefail
+{{ if .ollama.localmodels -}}
+  set -euo pipefail
 
-# Pretty print functions
-info()    { echo -e "\033[1;34m[INFO]\033[0m $*"; }
-warn()    { echo -e "\033[1;33m[WARN]\033[0m $*"; }
-error()   { echo -e "\033[1;31m[ERROR]\033[0m $*"; }
-success() { echo -e "\033[1;32m✅ $*\033[0m"; }
+  # Pretty print functions
+  info()    { echo -e "\033[1;34m[INFO]\033[0m $*"; }
+  warn()    { echo -e "\033[1;33m[WARN]\033[0m $*"; }
+  error()   { echo -e "\033[1;31m[ERROR]\033[0m $*"; }
+  success() { echo -e "\033[1;32m✅ $*\033[0m"; }
 
 
-info "Installing Ollama models"
-
-if type ollama >/dev/null 2>&1; then
   info "Installing Ollama models"
-  {{ range .ollama.models }} 
-    info "📥 Ollama pulling {{ . }} ..."
-	  ollama pull {{.}}
-  {{ end }}
 
-fi
+  if type ollama >/dev/null 2>&1; then
+    info "Installing Ollama models"
+    {{ range .ollama.models }} 
+      info "📥 Ollama pulling {{ . }} ..."
+      ollama pull {{.}}
+    {{ end }}
 
-success "Installed Ollama models"
+  fi
+
+  success "Installed Ollama models"
 
 {{ end -}}
 # vim: filetype=bash
